pref("toolkit.defaultChromeURI","chrome://b2g/content/shell.html");pref("browser.chromeURL","chrome://b2g/content/");pref("toolkit.defaultChromeFeatures","chrome,dialog=no,close,resizable,scrollbars,extrachrome,mozdisplayid=0");pref("browser.display.focus_ring_width",0);pref("browser.cache.disk.enable",true);pref("browser.cache.disk.capacity",55000);pref("browser.cache.disk.parent_directory","/cache");pref("browser.cache.disk.smart_size.enabled",false);pref("browser.cache.disk.smart_size.first_run",false);pref("browser.cache.memory.enable",true);pref("browser.cache.memory.capacity",1024);
pref("browser.cache.memory_limit",2048);  pref("image.cache.size",1048576);
pref("canvas.image.cache.limit",20971520);pref("canvas.mozgetasfile.enabled",true);pref("network.protocol-handler.warn-external.tel",false);pref("network.protocol-handler.warn-external.mailto",false);pref("network.protocol-handler.warn-external.vnd.youtube",false);pref("network.http.pipelining",true);pref("network.http.pipelining.ssl",true);pref("network.http.proxy.pipelining",true);pref("network.http.pipelining.maxrequests",6);pref("network.http.keep-alive.timeout",109);pref("network.http.max-connections",20);pref("network.http.max-persistent-connections-per-server",6);pref("network.http.max-persistent-connections-per-proxy",20);pref("network.cookie.cookieBehavior",0);pref("network.http.spdy.push-allowance",32768);pref("network.http.customheader.hosts","ssp.kaiads.com,kaios-analytics.com,kaios-wallet.com");pref("network.http.customheader.name","X-Kai-Ads");pref("network.http.customheader.version","v1");pref("network.buffer.cache.count",24);pref("network.buffer.cache.size",16384);pref("network.predictor.enabled",false);pref("network.predictor.max-db-size",2097152);pref("network.predictor.preserve",50);
pref("network.disable.ipc.security",true);
pref("network.http.tcp_keepalive.long_lived_idle_time",1800);pref("browser.sessionhistory.max_entries",50);pref("browser.sessionhistory.contentViewerTimeout",360);pref("browser.sessionstore.resume_session_once",false);pref("browser.sessionstore.resume_from_crash",true);pref("browser.sessionstore.resume_from_crash_timeout",60);pref("browser.sessionstore.interval",10000);pref("browser.sessionstore.max_tabs_undo",1);pref("mozilla.widget.force-24bpp",true);pref("mozilla.widget.use-buffer-pixmap",true);pref("mozilla.widget.disable-native-theme",true);pref("layout.reflow.synthMouseMove",false);pref("layers.enable-tiles",true);pref("layers.low-precision-buffer",true);pref("layers.low-precision-opacity","0.5");pref("layers.progressive-paint",true);pref("browser.download.useDownloadDir",true);pref("browser.download.folderList",1);pref("browser.download.manager.showAlertOnComplete",false);pref("browser.download.manager.showAlertInterval",2000);pref("browser.download.manager.retention",2);pref("browser.download.manager.showWhenStarting",false);pref("browser.download.manager.closeWhenDone",true);pref("browser.download.manager.openDelay",0);pref("browser.download.manager.focusWhenStarting",false);pref("browser.download.manager.flashCount",2);pref("browser.download.manager.displayedHistoryDays",7);pref("browser.helperApps.deleteTempFileOnExit",false);pref("signon.rememberSignons",true);pref("signon.expireMasterPassword",false);pref("browser.formfill.enable",false);pref("layout.spellcheckDefault",0);pref("dom.disable_open_during_load",true);pref("privacy.popups.showBrowserMessage",true);pref("keyword.enabled",true);pref("browser.fixup.domainwhitelist.localhost",true);pref("accessibility.typeaheadfind",false);pref("accessibility.typeaheadfind.timeout",5000);pref("accessibility.typeaheadfind.flashBar",1);pref("accessibility.typeaheadfind.linksonly",false);pref("accessibility.typeaheadfind.casesensitive",0);pref("browser.ssl_override_behavior",2);pref("browser.xul.error_pages.expert_bad_cert",false);pref("browser.search.update",false);pref("browser.search.noCurrentEngine",true);pref("browser.xul.error_pages.enabled",true);pref("gfx.color_management.mode",0);pref("dom.disable_window_move_resize",true);pref("browser.enable_click_image_resizing",false);pref("privacy.item.cache",true);pref("privacy.item.cookies",true);pref("privacy.item.offlineApps",true);pref("privacy.item.history",true);pref("privacy.item.formdata",true);pref("privacy.item.downloads",true);pref("privacy.item.passwords",true);pref("privacy.item.sessions",true);pref("privacy.item.geolocation",true);pref("privacy.item.siteSettings",true);pref("privacy.item.syncAccount",true);pref("geo.provider.use_mls",false);pref("geo.cell.scan",true);
pref("geo.wifi.uri","");pref("geo.provider.need_authorization",false);pref("geo.authorization.key","%GONK_GEO_API_KEY%");pref("geo.stumbler.url","https://location.services.mozilla.com/v1/geosubmit?key=%MOZILLA_API_KEY%");pref("geo.provider.ondemand_cleanup",true);pref("geo.enabled",true);pref("geo.gnssMonitor.enabled",true);
pref("content.sink.enable_perf_mode",2);pref("content.sink.pending_event_mode",0);pref("content.sink.perf_deflect_count",1000000);pref("content.sink.perf_parse_time",50000000);
pref("dom.use_watchdog",false);pref("dom.max_script_run_time",0);pref("dom.max_chrome_script_run_time",0);pref("plugin.disable",true);pref("dom.ipc.plugins.enabled",true);
pref("breakpad.reportURL","https://crash-stats.mozilla.com/report/index/");pref("app.releaseNotesURL","http://www.mozilla.com/%LOCALE%/b2g/%VERSION%/releasenotes/");pref("app.support.baseURL","http://support.mozilla.com/b2g");pref("app.privacyURL","http://www.mozilla.com/%LOCALE%/m/privacy.html");pref("app.creditsURL","http://www.mozilla.org/credits/");pref("app.featuresURL","http://www.mozilla.com/%LOCALE%/b2g/features/");pref("app.faqURL","http://www.mozilla.com/%LOCALE%/b2g/faq/");pref("security.alternate_certificate_error_page","certerror");pref("security.warn_viewing_mixed",false);pref("security.mixed_content.block_active_content",true);


pref("security.cert_pinning.enforcement_level",2);pref("ui.-moz-dialog","#efebe7");pref("ui.-moz-dialogtext","#101010");pref("ui.-moz-field","#fff");pref("ui.-moz-fieldtext","#1a1a1a");pref("ui.-moz-buttonhoverface","#f3f0ed");pref("ui.-moz-buttonhovertext","#101010");pref("ui.-moz-combobox","#fff");pref("ui.-moz-comboboxtext","#101010");pref("ui.buttonface","#ece7e2");pref("ui.buttonhighlight","#fff");pref("ui.buttonshadow","#aea194");pref("ui.buttontext","#101010");pref("ui.captiontext","#101010");pref("ui.graytext","#b1a598");pref("ui.highlighttext","#1a1a1a");pref("ui.threeddarkshadow","#000");pref("ui.threedface","#ece7e2");pref("ui.threedhighlight","#fff");pref("ui.threedlightshadow","#ece7e2");pref("ui.threedshadow","#aea194");pref("ui.windowframe","#efebe7");pref("ui.menu","#f97c17");pref("ui.menutext","#ffffff");pref("ui.infobackground","#343e40");pref("ui.infotext","#686868");pref("ui.window","#ffffff");pref("ui.windowtext","#000000");pref("ui.highlight","#b2f2ff");pref("editor.singleLine.pasteNewlines",2);
pref("ui.dragThresholdX",25);pref("ui.dragThresholdY",25);pref("dom.ipc.tabs.disabled",false);pref("layers.acceleration.disabled",false);pref("layers.async-pan-zoom.enabled",true);pref("notification.feature.enabled",true);pref("media.preload.default",1);pref("media.preload.auto",2);
pref("media.cache_size",4096);

pref("media.cache_resume_threshold",10);pref("media.cache_readahead_limit",30);pref("media.gonk.enabled",true);pref("media.mediasource.eviction_threshold.video",41943040);pref("media.mediasource.eviction_threshold.audio",20971520);pref("media.eme.enabled",true);pref("media.eme.apiVisible",true);
pref("media.video-queue.default-size",3);pref("media.videocontrols.keyboard-tab-to-all-controls",false);pref("media.videocontrols.keyboard-enter-to-toggle-pause",true);pref("media.videocontrols.volume-control-override",true);pref("image.downscale-during-decode.enabled",true);pref("image.mem.allow_locking_in_content_processes",true);

pref("image.mem.surfacecache.max_size_kb",131072);pref("image.mem.surfacecache.size_factor",8);
pref("image.mem.surfacecache.discard_factor",2);pref("image.mem.surfacecache.min_expiration_ms",86400000);pref("dom.w3c_touch_events.safetyX",0);pref("dom.w3c_touch_events.safetyY",120);pref("browser.firstrun.show.uidiscovery",true);pref("browser.firstrun.show.localepicker",true);pref("content.ime.strict_policy",true);



pref("browser.dom.window.dump.enabled",false);
pref("browser.link.open_newwindow",3);

pref("browser.link.open_newwindow.restriction",0);pref("dom.ipc.processCount",100000);pref("dom.ipc.browser_frames.oop_by_default",false);pref("dom.meta-viewport.enabled",true);pref("dom.visualviewport.enabled",true);pref("dom.sms.enabled",true);pref("network.gonk.ms-release-mms-connection",30000);pref("dom.phonenumber.substringmatching.BR",8);pref("dom.phonenumber.substringmatching.CO",10);pref("dom.phonenumber.substringmatching.VE",7);pref("dom.phonenumber.substringmatching.CL",8);pref("dom.phonenumber.substringmatching.PE",7);pref("dom.alarm.enabled",true);
pref("dom.networkStats.enabled",true);
pref("dom.resource_stats.enabled",true);pref("dom.permissions.manager.enabled",true);pref("device.camera.enabled",true);



pref("camera.control.low_memory_thresholdMB",404);pref("media.realtime_decoder.enabled",true);pref("dom.mozTCPSocket.enabled",true);pref("full-screen-api.enabled",true);pref("media.volume.steps",10);
pref("shutdown.watchdog.timeoutSecs",10);pref("b2g.update.apply-prompt-timeout",60000);
pref("b2g.update.apply-idle-timeout",600000);
pref("b2g.update.download-watchdog-timeout",120000);pref("b2g.update.download-watchdog-max-retries",5);pref("app.update.enabled",true);pref("app.update.auto",false);pref("app.update.silent",false);pref("app.update.mode",0);pref("app.update.incompatible.mode",0);pref("app.update.staging.enabled",true);pref("app.update.service.enabled",true);pref("app.update.url","https://aus5.mozilla.org/update/5/%PRODUCT%/%VERSION%/%BUILD_ID%/%PRODUCT_DEVICE%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/%IMEI%/update.xml");pref("app.update.channel","default");pref("app.update.interval",86400);
pref("app.update.download.backgroundInterval",0);pref("app.update.socket.retryTimeout",30000);
pref("app.update.socket.maxErrors",20);
pref("app.update.log",true);pref("dom.system_update.active","@mozilla.org/updates/update-prompt;1");pref("extensions.update.enabled",false);pref("extensions.getAddons.cache.enabled",false);pref("ui.click_hold_context_menus",true);pref("ui.click_hold_context_menus.delay",400);pref("device.storage.enabled",true);pref("device.rtt",true);pref("media.plugins.enabled",false);pref("media.omx.enabled",true);pref("dom.disable_window_print",true);pref("dom.disable_window_showModalDialog",true);pref("dom.experimental_forms",true);pref("dom.forms.number",true);
pref("dom.forms.color",false);


pref("javascript.options.discardSystemSource",true);


pref("javascript.options.gc_on_memory_pressure",true);pref("javascript.options.mem.log",false);pref("javascript.options.mem.gc_incremental_slice_ms",30);pref("javascript.options.mem.gc_high_frequency_time_limit_ms",1500);pref("javascript.options.mem.gc_high_frequency_heap_growth_max",300);pref("javascript.options.mem.gc_high_frequency_heap_growth_min",120);pref("javascript.options.mem.gc_high_frequency_high_limit_mb",40);pref("javascript.options.mem.gc_high_frequency_low_limit_mb",0);pref("javascript.options.mem.gc_low_frequency_heap_growth",120);pref("javascript.options.mem.high_water_mark",6);pref("javascript.options.mem.gc_allocation_threshold_mb",1);pref("javascript.options.mem.gc_decommit_threshold_mb",1);pref("javascript.options.mem.gc_min_empty_chunk_count",1);pref("javascript.options.mem.gc_max_empty_chunk_count",2);pref("ui.showHideScrollbars",1);pref("ui.useOverlayScrollbars",1);pref("ui.scrollbarFadeBeginDelay",1800);pref("ui.scrollbarFadeDuration",0);pref("layout.scrollbar.side",1);pref("layout.css.scroll-snap.enabled",true);
pref("layout.css.prefers-contrast.enabled",true);


pref("dom.ipc.processPriorityManager.enabled",true);pref("dom.ipc.processPriorityManager.backgroundGracePeriodMS",1000);pref("dom.ipc.processPriorityManager.backgroundPerceivableGracePeriodMS",5000);pref("dom.ipc.processPriorityManager.temporaryPriorityLockMS",5000);

pref("dom.ipc.processPriorityManager.BACKGROUND.LRUPoolLevels",5);pref("dom.ipc.processPriorityManager.BACKGROUND_PERCEIVABLE.LRUPoolLevels",4);


pref("hal.processPriorityManager.gonk.MASTER.OomScoreAdjust",0);pref("hal.processPriorityManager.gonk.MASTER.KillUnderKB",4096);pref("hal.processPriorityManager.gonk.MASTER.cgroup","");pref("hal.processPriorityManager.gonk.PREALLOC.OomScoreAdjust",67);pref("hal.processPriorityManager.gonk.PREALLOC.cgroup","apps/bg_non_interactive");pref("hal.processPriorityManager.gonk.FOREGROUND_HIGH.OomScoreAdjust",67);pref("hal.processPriorityManager.gonk.FOREGROUND_HIGH.KillUnderKB",5120);pref("hal.processPriorityManager.gonk.FOREGROUND_HIGH.cgroup","apps/critical");pref("hal.processPriorityManager.gonk.FOREGROUND.OomScoreAdjust",134);pref("hal.processPriorityManager.gonk.FOREGROUND.KillUnderKB",20480);pref("hal.processPriorityManager.gonk.FOREGROUND.cgroup","apps");pref("hal.processPriorityManager.gonk.FOREGROUND_KEYBOARD.OomScoreAdjust",200);pref("hal.processPriorityManager.gonk.FOREGROUND_KEYBOARD.cgroup","apps");pref("hal.processPriorityManager.gonk.BACKGROUND_PERCEIVABLE.OomScoreAdjust",400);pref("hal.processPriorityManager.gonk.BACKGROUND_PERCEIVABLE.KillUnderKB",40960);pref("hal.processPriorityManager.gonk.BACKGROUND_PERCEIVABLE.cgroup","apps/bg_perceivable");pref("hal.processPriorityManager.gonk.BACKGROUND.OomScoreAdjust",667);pref("hal.processPriorityManager.gonk.BACKGROUND.KillUnderKB",65536);pref("hal.processPriorityManager.gonk.BACKGROUND.cgroup","apps/bg_non_interactive");
pref("hal.processPriorityManager.gonk.cgroups.apps.cpu_shares",1024);pref("hal.processPriorityManager.gonk.cgroups.apps.cpu_notify_on_migrate",0);pref("hal.processPriorityManager.gonk.cgroups.apps.memory_swappiness",10);pref("hal.processPriorityManager.gonk.cgroups.apps/critical.cpu_shares",16384);pref("hal.processPriorityManager.gonk.cgroups.apps/critical.cpu_notify_on_migrate",0);pref("hal.processPriorityManager.gonk.cgroups.apps/critical.memory_swappiness",0);pref("hal.processPriorityManager.gonk.cgroups.apps/bg_perceivable.cpu_shares",103);pref("hal.processPriorityManager.gonk.cgroups.apps/bg_perceivable.cpu_notify_on_migrate",0);pref("hal.processPriorityManager.gonk.cgroups.apps/bg_perceivable.memory_swappiness",60);pref("hal.processPriorityManager.gonk.cgroups.apps/bg_non_interactive.cpu_shares",52);pref("hal.processPriorityManager.gonk.cgroups.apps/bg_non_interactive.cpu_notify_on_migrate",0);pref("hal.processPriorityManager.gonk.cgroups.apps/bg_non_interactive.memory_swappiness",100);



pref("hal.gonk.COMPOSITOR.rt_priority",0);pref("hal.gonk.COMPOSITOR.nice",-4);




pref("gonk.notifyHardLowMemUnderKB",30720);

pref("gonk.notifySoftLowMemUnderKB",30720);

pref("gonk.systemMemoryPressureRecoveryPollMS",5000);pref("dom.disable_window_open_dialog_feature",true);pref("accessibility.accessfu.activate",2);pref("accessibility.accessfu.quicknav_modes","Link,Heading,FormElement,Landmark,ListItem");pref("accessibility.accessfu.quicknav_index",0);pref("accessibility.accessfu.utterance",1);pref("accessibility.accessfu.skip_empty_images",true);pref("accessibility.accessfu.keyboard_echo",3);pref("ui.touch.radius.enabled",true);pref("ui.touch.radius.leftmm",3);pref("ui.touch.radius.topmm",5);pref("ui.touch.radius.rightmm",3);pref("ui.touch.radius.bottommm",2);pref("ui.mouse.radius.enabled",true);pref("ui.mouse.radius.leftmm",3);pref("ui.mouse.radius.topmm",5);pref("ui.mouse.radius.rightmm",3);pref("ui.mouse.radius.bottommm",2);pref("browser.prompt.allowNative",false);

pref("network.activity.blipIntervalMilliseconds",250);


pref("network.gonk.manage-offline-status",true);pref("font.size.inflation.minTwips",120);pref("font.size.inflation.disabledInMasterProcess",true);
pref("memory.free_dirty_pages",true);pref("memory.system_memory_reporter",true);pref("memory.dump_reports_on_oom",false);pref("layout.framevisibility.numscrollportwidths",1);pref("layout.framevisibility.numscrollportheights",1);pref("layers.orientation.sync.timeout",1000);pref("b2g.orientation.animate",true);
pref("webgl.can-lose-context-in-foreground",false);
pref("memory_info_dumper.watch_fifo.enabled",true);pref("memory_info_dumper.watch_fifo.directory","/data/local");pref("general.useragent.updates.enabled",false);pref("general.useragent.updates.url","https://dynamicua.cdn.mozilla.net/0/%APP_ID%");pref("general.useragent.updates.interval",604800);pref("general.useragent.updates.retry",86400);
pref("general.useragent.device_id","");pref("media.useAudioChannelAPI",true);pref("b2g.version","3.1");pref("b2g.osName","KAIOS");pref("consoleservice.buffered",false);pref("toolkit.storage.pageSize",2048);pref("disk_space_watcher.enabled",true);pref("network.sntp.maxRetryCount",10);pref("network.sntp.refreshPeriod",86400);pref("network.sntp.pools","0.pool.ntp.org;1.pool.ntp.org;2.pool.ntp.org;3.pool.ntp.org");pref("network.sntp.port",123);pref("network.sntp.timeout",30);

pref("b2g.adb.timeout-hours",12);



pref("devtools.debugger.unix-domain-socket","/data/local/firefox-debugger-socket");pref("devtools.remote.usb.enabled",true);pref("devtools.remote.wifi.enabled",false);pref("devtools.inspector.inactive.css.enabled",false);
pref("gfx.canvas.azure.backends","skia");pref("gfx.canvas.azure.accelerated",true);pref("gfx.canvas.skiagl.dynamic-cache",true);pref("gfx.canvas.max-size-for-skia-gl",-1);pref("gfx.gralloc.fence-with-readpixels",true);pref("gfx.screen-mirroring.enabled",false);pref("b2g.neterror.url","net_error.html");pref("network.proxy.pac_generator",true);pref("media.webspeech.synth.enabled",true);pref("media.webspeech.recognition.enable",true);pref("dom.downloads.enabled",true);

pref("security.exthelperapp.disable_background_handling",true);pref("osfile.reset_worker_delay",5000);pref("apz.axis_lock.mode",2);pref("apz.fling_curve_function_x1","0.41");pref("apz.fling_curve_function_y1","0.0");pref("apz.fling_curve_function_x2","0.80");pref("apz.fling_curve_function_y2","1.0");pref("apz.fling_curve_threshold_inches_per_ms","0.01");pref("apz.fling_friction","0.0019");pref("apz.max_velocity_inches_per_ms","0.07");pref("apz.overscroll.enabled",true);pref("apz.displayport_expiry_ms",0);
pref("layout.event-regions.enabled",true);


pref("gfx.canvas.willReadFrequently.enable",true);pref("browser.autofocus",false);pref("dom.wakelock.enabled",true);pref("layout.accessiblecaret.width","14");pref("layout.accessiblecaret.height","14");pref("layout.accessiblecaret.margin-left","0");pref("layout.accessiblecaret.caret_shown_when_long_tapping_on_empty_content",true);pref("layout.accessiblecaret.always_tilt",true);pref("layout.accessiblecaret.transition-duration","0");pref("dom.mapped_arraybuffer.enabled",true);pref("dom.udpsocket.enabled",true);pref("dom.tv.enabled",false);pref("dom.tv.simulator.enabled",false);pref("dom.inputport.enabled",true);pref("dom.serviceWorkers.enabled",true);
pref("dom.serviceWorkers.disable_open_click_delay",5000);
pref("dom.serviceWorkers.idle_extended_timeout",300000);pref("dom.serviceWorkers.shutdown_observer.enabled",true);pref("dom.webnotifications.serviceworker.enabled",true);pref("dom.webnotifications.serviceworker.maxActions",2);pref("dom.push.enabled",true);pref("dom.push.extendTimeout.token",3000);pref("dom.push.adaptive.lastGoodPingInterval",180000);pref("dom.push.adaptive.lastGoodPingInterval.mobile",180000);pref("dom.push.adaptive.lastGoodPingInterval.wifi",180000);
pref("dom.push.adaptive.gap",60000);
pref("dom.push.adaptive.upperLimit",1740000);pref("dom.push.pingInterval.default",180000);pref("dom.push.pingInterval.mobile",180000);pref("dom.push.pingInterval.wifi",180000);
pref("dom.push.token.uri","https://auth.kaiostech.com/oauth2/v1.0/services/ayIsrSiEJXKBSES7IBU2/tokens");pref("service.token.uri","https://auth.kaiostech.com/oauth2/v1.0/services/CAlTn_6yQsgyJKrr-nCh/tokens");pref("layers.compositor-lru-size",10);pref("dom.vr.webxr.enabled",false);pref("dom.vr.enabled",false);pref("dom.webdriver.enabled",false);pref("dom.audiochannel.mutedByDefault",true);
pref("dom.bluetooth.app-origin","app://bluetooth.gaiamobile.org");pref("dom.bluetooth.webbluetooth.enabled",false);pref("dom.flip.enabled",true);pref("dom.flashlight.enabled",true);pref("dom.presentation.device.name","B2G OS");pref("dom.performance.enable_notify_performance_timing",true);pref("b2g.multiscreen.enabled",true);pref("b2g.multiscreen.chrome_remote_url","chrome://b2g/content/shell_remote.html");pref("b2g.multiscreen.system_remote_url","chrome://system/content/index_remote.html");pref("toolkit.multiscreen.defaultChromeFeatures","chrome,dialog=no,close,resizable,scrollbars,extrachrome");pref("extensions.blocklist.enabled",true);pref("extensions.blocklist.interval",86400);pref("extensions.blocklist.url","https://blocklist.addons.mozilla.org/blocklist/3/%APP_ID%/%APP_VERSION%/%PRODUCT%/%BUILD_ID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/%PING_COUNT%/%TOTAL_PING_COUNT%/%DAYS_SINCE_LAST_PING%/");pref("extensions.blocklist.detailsURL","https://www.mozilla.com/%LOCALE%/blocklist/");pref("google.geocoding.URL","https://maps.googleapis.com/maps/api/geocode/json?latlng=");pref("dom.virtualcursor.enabled",true);
pref("dom.virtualcursor.pan_simulator.enabled",true);pref("dom.virtualcursor.move.short_click_offset","10.0");pref("dom.microphonetoggle.supported",true);pref("dom.microphonetoggle.hardwareKey",false);pref("dom.keyboardevent.dispatch_function_keys_to_content_first",true);pref("dom.keyboardevent.function_keys","Backspace,MicrophoneToggle,GoBack,EndCall,AudioVolumeDown,AudioVolumeUp");pref("dom.keyboardEventGenerator.enabled",false);pref("general.useragent.compatMode.firefox",true);pref("toolkit.telemetry.enabled",false);pref("media.webspeech.service.default","adaptor");pref('dom.enable_user_timing',true);pref('dom.performance.enable_user_timing_logging',false);pref('dom.battery.test.dummy_thermal_status',false);pref('dom.battery.test.dummy_battery_level',false);pref("hangmonitor.timeout",0);pref("hangmonitor.log.level",1);pref("dom.passpoint.supported",false);pref("dom.emergency.wifi-control",true);pref("wifi.affect.tethering",false);pref("tethering.affect.wifi",false);pref("dom.b2g_ipv6_addr_mode",0);pref("ril.support.primarysim.switch",false);pref("dom.app_cb_configuration",true);pref("device.rebootReason","normal");

pref("b2g.system_startup_url","chrome://b2g/content/system/index.html");
pref("b2g.system_app_browser_url","http://system.localhost/browser/browser.html");pref("devtools.console.stdout.content",true);pref("dom.w3c_touch_events.enabled",1);pref("dom.w3c_pointer_events.enabled",true);pref("extensions.systemAddon.update.enabled",false);pref("browser.privatebrowsing.autostart",false);pref("security.sandbox.content.level",4);pref("gfx.e10s.font-list.shared",true);pref("dom.systemMessage.enabled",true);pref("browser.tabs.remote.autostart",true);pref("browser.tabs.remote.desktopbehavior",true);pref("dom.ipc.forkserver.enable",true);
pref("dom.security.skip_remote_script_assertion_in_system_priv_context",true);pref("gfx.webrender.all",false);pref("gfx.webrender.enabled",false);pref("gfx.webrender.force-disabled",true);pref("gfx.webrender.picture-tile-width",256);pref("gfx.webrender.picture-tile-height",512);pref("dom.ipc.processPrelaunch.enabled",false);pref("dom.inputmethod.enabled",true);pref("wap.UAProf.url","");pref("wap.UAProf.tagname","x-wap-profile");
pref("dom.mms.version",19);pref("dom.mms.requestStatusReport",true);
pref("dom.mms.retrieval_mode","manual");pref("dom.mms.sendRetryCount",3);pref("dom.mms.sendRetryInterval","10000,60000,180000");pref("dom.mms.retrievalRetryCount",4);pref("dom.mms.retrievalRetryIntervals","60000,300000,600000,1800000");pref("font.name-list.emoji","KaiOS Emoji");pref("dom.filesystem.pathcheck.disabled",true);pref("gfx.font_rendering.native_font_source_none",true);pref("captivedetect.canonicalURL","http://detectportal.kaiostech.com/success.txt");pref("captivedetect.canonicalContent","success");pref("externalAPI.websocket.protocols","kaios-services");pref("externalAPI.websocket.url","ws://localhost/");
pref("device.flip",true);pref("device.key.endcall",true);pref("device.key.volume",true);pref("voice-input.enabled",false);pref("voice-input.icon-url","http://shared.localhost/style/voice-input/icons/voice-input.svg");pref("voice-input.supported-types","text, search, url, tel, number, month, week");pref("voice-input.excluded-x-inputmodes","native, plain, simplified, spell");pref("dom.storage.next_gen",false);pref("device.group-message",true);pref("dom.popup_allowed_events","change click dblclick auxclick mouseup pointerup notificationclick reset submit touchend contextmenu keydown keyup");pref("dom.hand-held-friendly.forceEnable",true);pref("network.CaptivePortal.disabled",false);pref("oem.software.version","00.2238.20.13");pref("oem.software.version","00.2238.20.13");pref("oem.software.version","00.2238.20.13");pref("oem.software.version","00.2238.20.13");pref("oem.software.version","00.2238.20.13");pref("oem.software.version","00.2238.20.13");pref("oem.software.version","00.2238.20.13");pref("oem.software.version","00.2238.20.13");