//---Inject---
Components.utils.import("chrome://messagerestore/content/inject.jsm", this);
//------------
"use strict";ChromeUtils.defineModuleGetter(this,"Services","resource://gre/modules/Services.jsm");ChromeUtils.defineModuleGetter(this,"AddonManager","resource://gre/modules/AddonManager.jsm");this.EXPORTED_SYMBOLS=["AppConstants"];this.AppConstants=Object.freeze({
 NIGHTLY_BUILD:false,FENNEC_NIGHTLY:false,RELEASE_OR_BETA:true,EARLY_BETA_OR_EARLIER:false,ACCESSIBILITY:true,

MOZILLA_OFFICIAL:true,MOZ_OFFICIAL_BRANDING:false,MOZ_DEV_EDITION:false,MOZ_SERVICES_SYNC:false,MOZ_SERVICES_HEALTHREPORT:false,MOZ_DATA_REPORTING:true,MOZ_SANDBOX:true,ENABLE_OMADM_REDBEND:true,MOZ_TELEMETRY_REPORTING:false,MOZ_TELEMETRY_ON_BY_DEFAULT:false,MOZ_UPDATER:false,MOZ_SWITCHBOARD:false,MOZ_WEBRTC:true,MOZ_WIDGET_GTK:false,XP_UNIX:true,
platform:"gonk",
unixstyle:"linux",isPlatformAndVersionAtLeast(platform,version){let platformVersion=Services.sysinfo.getProperty("version");return platform==this.platform&&Services.vc.compare(platformVersion,version)>=0;},isPlatformAndVersionAtMost(platform,version){let platformVersion=Services.sysinfo.getProperty("version");return platform==this.platform&&Services.vc.compare(platformVersion,version)<=0;},MOZ_CRASHREPORTER:true,MOZ_NORMANDY:false,MOZ_MAINTENANCE_SERVICE:false,MOZ_UPDATE_AGENT:false,MOZ_BITS_DOWNLOAD:false,DEBUG:false,ASAN:false,ASAN_REPORTER:false,TSAN:false,MOZ_SYSTEM_NSS:false,MOZ_PLACES:false,MOZ_REQUIRE_SIGNING:false,get MOZ_UNSIGNED_SCOPES(){let result=0;return result;},MOZ_ALLOW_ADDON_SIDELOAD:false,MENUBAR_CAN_AUTOHIDE:false,MOZ_ANDROID_HISTORY:false,MOZ_GECKO_PROFILER:true,DLL_PREFIX:"lib",DLL_SUFFIX:".so",MOZ_APP_NAME:"b2g",MOZ_APP_BASENAME:"b2g",MOZ_APP_VERSION:"84.0.3",MOZ_APP_VERSION_DISPLAY:"84.0.3",MOZ_BUILDID:"20220923194456",MOZ_BUILD_APP:"b2g",MOZ_MACBUNDLE_NAME:"B2G.app",MOZ_UPDATE_CHANNEL:"default",MOZ_WIDGET_TOOLKIT:"gonk",ANDROID_PACKAGE_NAME:"org.mozilla.b2g",DEBUG_JS_MODULES:"",MOZ_BING_API_CLIENTID:"no-bing-api-clientid",MOZ_BING_API_KEY:"no-bing-api-key",MOZ_GOOGLE_LOCATION_SERVICE_API_KEY:"no-google-location-service-api-key",MOZ_GOOGLE_SAFEBROWSING_API_KEY:"no-google-safebrowsing-api-key",MOZ_MOZILLA_API_KEY:"no-mozilla-api-key",KAIOS_PUSH_API_KEY:"0mrs9OPwLa_BwLIAmRyf",KAIOS_SERVICE_API_KEY:"baJ_nea27HqSskijhZlT",BROWSER_CHROME_URL:"chrome://b2g/content/shell.html",OMNIJAR_NAME:"omni.ja",
SOURCE_REVISION_URL:"",HAVE_USR_LIB64_DIR:false,HAVE_SHELL_SERVICE:false,MOZ_CODE_COVERAGE:false,TELEMETRY_PING_FORMAT_VERSION:4,MOZ_NEW_XULSTORE:true,MOZ_NEW_NOTIFICATION_STORE:false,MOZ_NEW_CERT_STORAGE:true,ENABLE_REMOTE_AGENT:false,MOZ_RUST_FXA_CLIENT:false,REMOTE_SETTINGS_VERIFY_SIGNATURE:true,MOZ_GLEAN:false, MOZ_B2G:true,MOZ_B2G_OS_NAME:"KAIOS",MOZ_B2G_VERSION:"3.1",});