const{XPCOMUtils}=ChromeUtils.import("resource://gre/modules/XPCOMUtils.jsm");const{ComponentUtils}=ChromeUtils.import("resource://gre/modules/ComponentUtils.jsm");const{Services}=ChromeUtils.import("resource://gre/modules/Services.jsm");const{OS}=ChromeUtils.import("resource://gre/modules/osfile.jsm");const IMAGE_FILTERS=["image/gif","image/jpeg","image/pjpeg","image/png","image/svg+xml","image/tiff","image/vnd.microsoft.icon",];const VIDEO_FILTERS=["video/mpeg","video/mp4","video/ogg","video/quicktime","video/webm","video/x-matroska","video/x-ms-wmv","video/x-flv",];const AUDIO_FILTERS=["audio/basic","audio/L24","audio/mp4","audio/mpeg","audio/ogg","audio/vorbis","audio/vnd.rn-realaudio","audio/vnd.wave","audio/webm",];function FilePicker(){}
FilePicker.prototype={classID:Components.ID("{436ff8f9-0acc-4b11-8ec7-e293efba3141}"),QueryInterface:ChromeUtils.generateQI([Ci.nsIFilePicker]),mParent:undefined,mExtraProps:undefined,mFilterTypes:undefined,mFileEnumerator:undefined,mFilePickerShownCallback:undefined,init(parent,title,mode){this.mParent=parent;this.mExtraProps={};this.mFilterTypes=[];this.mMode=mode;if(mode!=Ci.nsIFilePicker.modeOpen&&mode!=Ci.nsIFilePicker.modeOpenMultiple){throw Components.Exception("",Cr.NS_ERROR_NOT_IMPLEMENTED);}},get domFileOrDirectoryEnumerator(){return this.mFilesEnumerator;},get domFileOrDirectory(){return this.mFilesEnumerator?this.mFilesEnumerator.mFiles[0]:null;},get mode(){return this.mMode;},appendFilters(filterMask){
 if(filterMask&Ci.nsIFilePicker.filterImages){this.mFilterTypes=this.mFilterTypes.concat(IMAGE_FILTERS);this.mExtraProps.nocrop=true;}


 
if(filterMask&Ci.nsIFilePicker.filterVideo){this.mFilterTypes=this.mFilterTypes.concat(VIDEO_FILTERS);}
if(filterMask&Ci.nsIFilePicker.filterAudio){this.mFilterTypes=this.mFilterTypes.concat(AUDIO_FILTERS);}
if(filterMask&Ci.nsIFilePicker.filterAll){this.mExtraProps.nocrop=true;}},appendFilter(title,extensions){ let imageList=["BMP Image","GIF Image","JPEG Image","PNG Image","TIFF Image",];let prefixReg=/\*\./g;if(imageList.includes(title)){if(extensions.includes("*.")){extensions=extensions.replace(prefixReg,"image/");}
this.mFilterTypes=this.mFilterTypes.concat(extensions.split(/[\s;]+/));this.mExtraProps.nocrop=true;}},open(aFilePickerShownCallback){this.mFilePickerShownCallback=aFilePickerShownCallback;Services.cpmm.addMessageListener("file-picked",this);let detail={};if(this.mFilterTypes){detail.type=this.mFilterTypes;}
for(let prop in this.mExtraProps){if(!(prop in detail)){detail[prop]=this.mExtraProps[prop];}}
Services.cpmm.sendAsyncMessage("file-picker",detail);},fireSuccess(file){this.mFilesEnumerator={QueryInterface:ChromeUtils.generateQI([Ci.nsISimpleEnumerator]),mFiles:[file],mIndex:0,hasMoreElements(){return this.mIndex<this.mFiles.length;},getNext(){if(this.mIndex>=this.mFiles.length){throw Components.Exception("",Cr.NS_ERROR_FAILURE);}
return this.mFiles[this.mIndex++];},};if(this.mFilePickerShownCallback){this.mFilePickerShownCallback.done(Ci.nsIFilePicker.returnOK);this.mFilePickerShownCallback=null;}},fireError(){if(this.mFilePickerShownCallback){this.mFilePickerShownCallback.done(Ci.nsIFilePicker.returnCancel);this.mFilePickerShownCallback=null;}},receiveMessage(message){if(message.name!=="file-picked"){return;}
Services.cpmm.removeMessageListener("file-picked",this);let data=message.data;if(!data.success||!data.result.blob){this.fireError();return;}

let name=data.result.name;if(!name&&data.result.blob instanceof this.mParent.File&&data.result.blob.name){name=data.result.blob.name;}
if(name){let names=OS.Path.split(name);name=names.components[names.components.length-1];}
if(!name){name="blob";if(data.result.blob.type){let mimeSvc=Cc["@mozilla.org/mime;1"].getService(Ci.nsIMIMEService);let mimeInfo=mimeSvc.getFromTypeAndExtension(data.result.blob.type,"");if(mimeInfo){name+="."+mimeInfo.primaryExtension;}}}
let file=new this.mParent.File([data.result.blob],name,{type:data.result.blob.type,});if(file){this.fireSuccess(file);}else{this.fireError();}},};this.NSGetFactory=ComponentUtils.generateNSGetFactory([FilePicker]);